/// <reference types="@figma/plugin-typings" />
import { SwiftBloxNode, UDim2, Vector2Data, Color3, GradientData } from './types';

function round(value: number, decimals = 3): number {
  return Number(value.toFixed(decimals));
}

function figmaColorToRoblox(paint: SolidPaint): Color3 {
  return {
    R: Math.round(paint.color.r * 255),
    G: Math.round(paint.color.g * 255),
    B: Math.round(paint.color.b * 255),
    A: paint.opacity !== undefined ? paint.opacity : 1
  };
}

function parseGradient(fill: GradientPaint, width: number, height: number): GradientData | undefined {
  if (!fill.gradientStops || fill.gradientStops.length === 0) return undefined;
  const colorPoints = fill.gradientStops.map(stop => ({ Position: Number(stop.position.toFixed(4)), Color: { R: Math.round(stop.color.r * 255), G: Math.round(stop.color.g * 255), B: Math.round(stop.color.b * 255), A: stop.color.a } }));
  const transparencyPoints = fill.gradientStops.map(stop => ({ Position: Number(stop.position.toFixed(4)), Transparency: 1 - stop.color.a }));

  let type: GradientData['Type'] = 'Linear';
  if (fill.type === 'GRADIENT_RADIAL') type = 'Radial';
  else if (fill.type === 'GRADIENT_ANGULAR') type = 'Conical';

  let rotation = 0;
  const fillAny = fill as any;
  if (fill.type === 'GRADIENT_LINEAR' && fillAny.gradientHandlePositions && fillAny.gradientHandlePositions.length >= 2) {
    const dx = (fillAny.gradientHandlePositions[1].x - fillAny.gradientHandlePositions[0].x) * (width || 1);
    const dy = (fillAny.gradientHandlePositions[1].y - fillAny.gradientHandlePositions[0].y) * (height || 1);
    rotation = (Math.atan2(dy, dx) * 180) / Math.PI;
    if (rotation < 0) rotation += 360;
    rotation = Number(rotation.toFixed(2));
  }
  return { Type: type, Rotation: rotation, ColorPoints: colorPoints, TransparencyPoints: transparencyPoints };
}

function calculateUDim2(node: SceneNode, parentNode: SceneNode | null): { Size: UDim2; Position: UDim2; AnchorPoint?: Vector2Data } {
  if (!('absoluteBoundingBox' in node) || !node.absoluteBoundingBox) return { Size: { ScaleX: 0, OffsetX: 0, ScaleY: 0, OffsetY: 0 }, Position: { ScaleX: 0, OffsetX: 0, ScaleY: 0, OffsetY: 0 }, AnchorPoint: { X: 0, Y: 0 } };
  
  const width = round(node.absoluteBoundingBox.width);
  const height = round(node.absoluteBoundingBox.height);

  if (!parentNode || !('absoluteBoundingBox' in parentNode) || !parentNode.absoluteBoundingBox) {
    return { Size: { ScaleX: 0, OffsetX: width, ScaleY: 0, OffsetY: height }, Position: { ScaleX: 0.5, OffsetX: 0, ScaleY: 0.5, OffsetY: 0 }, AnchorPoint: { X: 0.5, Y: 0.5 } };
  }

  return {
    Size: { ScaleX: 0, OffsetX: width, ScaleY: 0, OffsetY: height },
    Position: { ScaleX: 0, OffsetX: round(node.absoluteBoundingBox.x - parentNode.absoluteBoundingBox.x), ScaleY: 0, OffsetY: round(node.absoluteBoundingBox.y - parentNode.absoluteBoundingBox.y) },
    AnchorPoint: { X: 0, Y: 0 }
  };
}

export async function parseNode(node: SceneNode, parentNode: SceneNode | null): Promise<SwiftBloxNode | null> {
  if (!node.visible) return null;

  let className = 'Frame';
  const rawName = node.name.toLowerCase();
  
  // DETECT SVGS, ICONS, AND VECTORS GENERATED BY HTML-TO-FIGMA
  const isSvgOrIcon = rawName.includes('svg') || rawName.includes('icon') || rawName.includes('star') || 
                      node.type === 'VECTOR' || node.type === 'BOOLEAN_OPERATION' || node.type === 'ELLIPSE' || node.type === 'POLYGON';

  if (node.type === 'TEXT') className = 'TextLabel';
  if (isSvgOrIcon) className = 'ImageLabel';

  const isImageNode = className === 'ImageLabel';
  const nodeBox = ('absoluteBoundingBox' in node && node.absoluteBoundingBox) ? node.absoluteBoundingBox : { width: 0, height: 0 };
  const { Size, Position, AnchorPoint } = calculateUDim2(node, parentNode);

  const robloxNode: any = {
    Name: node.name.replace(/[^a-zA-Z0-9 ]/g, '').trim() || 'Element',
    ClassName: className,
    Size, Position, AnchorPoint,
    Rotation: 'rotation' in node && typeof node.rotation === 'number' && Math.abs(node.rotation) > 0.001 ? Number(node.rotation.toFixed(3)) : undefined,
    Children: []
  };

  let solidFill: SolidPaint | undefined;
  let gradientFills: GradientPaint[] = [];

  if ('fills' in node && Array.isArray(node.fills)) {
    const visibleFills = node.fills.filter((f: Paint) => f.visible !== false);
    solidFill = visibleFills.find((f: Paint) => f.type === 'SOLID') as SolidPaint | undefined;
    gradientFills = visibleFills.filter((f: Paint) => f.type === 'GRADIENT_LINEAR' || f.type === 'GRADIENT_RADIAL' || f.type === 'GRADIENT_ANGULAR') as GradientPaint[];
  }

  if (gradientFills.length > 0) {
    robloxNode.Gradient = parseGradient(gradientFills[0], nodeBox.width, nodeBox.height);
    robloxNode.BackgroundColor3 = { R: 255, G: 255, B: 255, A: 1 };
    robloxNode.BackgroundTransparency = 0;
  } else if (solidFill && !isImageNode) {
    const color = figmaColorToRoblox(solidFill);
    robloxNode.BackgroundColor3 = color;
    robloxNode.BackgroundTransparency = 1 - color.A;
  } else if (isImageNode) {
    // FIX: Force ImageLabels to be fully transparent so they don't block the UI behind them
    robloxNode.BackgroundTransparency = 1;
  } else {
    robloxNode.BackgroundTransparency = 1;
  }

  if (node.type === 'TEXT' && !isImageNode) {
    robloxNode.Text = node.characters;
    robloxNode.TextSize = typeof node.fontSize === 'number' ? node.fontSize : 14;
    robloxNode.BackgroundTransparency = 1;
    delete robloxNode.BackgroundColor3;

    if (solidFill) robloxNode.TextColor3 = figmaColorToRoblox(solidFill);

    if (node.fontName && typeof node.fontName !== 'symbol') {
      const rawStyle = node.fontName.style.trim().toLowerCase();
      robloxNode.FontFamily = node.fontName.family.trim().replace(/[^a-zA-Z0-9_-]/g, '');
      robloxNode.FontStyle = node.fontName.style;
      
      if (rawStyle.includes('heavy') || rawStyle.includes('black')) robloxNode.FontWeight = 'Heavy';
      else if (rawStyle.includes('extra bold')) robloxNode.FontWeight = 'ExtraBold';
      else if (rawStyle.includes('semi bold') || rawStyle.includes('semibold')) robloxNode.FontWeight = 'SemiBold';
      else if (rawStyle.includes('bold')) robloxNode.FontWeight = 'Bold';
      else if (rawStyle.includes('medium')) robloxNode.FontWeight = 'Medium';
      else if (rawStyle.includes('light')) robloxNode.FontWeight = 'Light';
      else if (rawStyle.includes('thin')) robloxNode.FontWeight = 'Thin';
      else robloxNode.FontWeight = 'Regular';
    }

    robloxNode.TextXAlignment = node.textAlignHorizontal === 'RIGHT' ? 'Right' : (node.textAlignHorizontal === 'CENTER' ? 'Center' : 'Left');
    robloxNode.TextYAlignment = node.textAlignVertical === 'BOTTOM' ? 'Bottom' : (node.textAlignVertical === 'TOP' ? 'Top' : 'Center');
  }

  if ('strokes' in node && Array.isArray(node.strokes) && node.strokes.length > 0) {
    const solidStroke = node.strokes.find((s: Paint) => s.type === 'SOLID' && s.visible !== false) as SolidPaint | undefined;
    if (solidStroke && 'strokeWeight' in node && typeof node.strokeWeight === 'number') {
      robloxNode.Stroke = { Color: figmaColorToRoblox(solidStroke), Thickness: node.strokeWeight };
    }
  }

  if ('cornerRadius' in node && typeof node.cornerRadius === 'number' && node.cornerRadius > 0) {
    robloxNode.CornerRadius = node.cornerRadius;
  }

  if ('children' in node && !isImageNode) {
    for (const child of node.children) {
      const childNode = await parseNode(child, node);
      if (childNode) robloxNode.Children.push(childNode);
    }
  }

  return robloxNode;
}